import { estimateCost } from "./pricing";
import type { UsageBucket, UsageSession } from "./types";
export interface Totals { tokens: number; input: number; output: number; cached: number; reasoning: number; cost: number; priced: number; }
export interface SessionTotals { active: number; duration: number; sessions: number; messages: number; userMessages: number; }
export function totalsOf(buckets: UsageBucket[]): Totals {
  return buckets.reduce<Totals>((t, b) => { t.tokens += b.inputTokens + b.cachedInputTokens + b.outputTokens + b.reasoningOutputTokens; t.input += b.inputTokens; t.output += b.outputTokens; t.cached += b.cachedInputTokens; t.reasoning += b.reasoningOutputTokens; const cost = estimateCost(b); if (cost !== null) { t.cost += cost; t.priced++; } return t; }, { tokens: 0, input: 0, output: 0, cached: 0, reasoning: 0, cost: 0, priced: 0 });
}
export function cacheHitRate(input: number, cached: number) { const denominator = input + cached; return denominator > 0 ? cached / denominator : 0; }
export function sessionTotalsOf(sessions: UsageSession[]): SessionTotals { return sessions.reduce((t, s) => ({ active: t.active + s.activeSeconds, duration: t.duration + s.durationSeconds, sessions: t.sessions + 1, messages: t.messages + s.messageCount, userMessages: t.userMessages + s.userMessageCount }), { active: 0, duration: 0, sessions: 0, messages: 0, userMessages: 0 }); }
export function groupBuckets(buckets: UsageBucket[], field: "source" | "provider" | "model" | "hostname" | "project") { const groups = new Map<string, UsageBucket[]>(); for (const b of buckets) { const key = b[field] || "unknown"; groups.set(key, [...(groups.get(key) ?? []), b]); } return [...groups].map(([name, rows]) => ({ name, ...totalsOf(rows) })).sort((a,b) => b.tokens-a.tokens); }
export function groupProviders(buckets: UsageBucket[]) { const groups=new Map<string,UsageBucket[]>();for(const bucket of buckets){const key=bucket.provider||"unknown";groups.set(key,[...(groups.get(key)??[]),bucket]);}return [...groups].map(([provider,rows])=>({provider,...totalsOf(rows),sources:groupBuckets(rows,"source")})).sort((a,b)=>b.tokens-a.tokens); }
export const groupBySource = (b: UsageBucket[]) => groupBuckets(b, "source").map(v => ({ ...v, source: v.name, models: new Set(b.filter(x => x.source === v.name).map(x => x.model)).size }));
export function seriesOf(buckets: UsageBucket[], range: string) { const hourly = range === "today" || range === "24h"; const map = new Map<string, UsageBucket[]>(); for (const b of buckets) { const date = new Date(b.bucketStart); const key = hourly ? `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}-${date.getHours()}` : `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; map.set(key, [...(map.get(key) ?? []), b]); } return [...map].map(([key, rows]) => { const date = new Date(rows[0].bucketStart); return { key, timestamp:date.getTime(), label: hourly ? `${String(date.getHours()).padStart(2,"0")}:00` : `${date.getMonth()+1}/${date.getDate()}`, ...totalsOf(rows) }; }).sort((a,b) => a.timestamp-b.timestamp); }
export const formatTokens = (value: number) => !Number.isFinite(value) ? "--" : value >= 1e9 ? `${(value/1e9).toFixed(1)}B` : value >= 1e6 ? `${(value/1e6).toFixed(1)}M` : value >= 1e3 ? `${(value/1e3).toFixed(1)}K` : Math.round(value).toLocaleString();
export const formatCost = (value: number) => Number.isFinite(value) ? `$${value.toFixed(2)}` : "--";
export const formatDuration = (seconds: number) => { const safe = Number.isFinite(seconds) ? Math.max(0, Math.floor(seconds)) : 0; const h = Math.floor(safe/3600); const m = Math.floor(safe%3600/60); return `${h}h ${m}m`; };
export const displaySource = (source: string) => ({ codex: "Codex", "claude-code": "Claude Code", workbuddy: "WorkBuddy", "kimi-code": "Kimi Code", kimi: "Kimi Code", zcode: "智谱", zai: "智谱", zhipu: "智谱", reasonix: "Reasonix", dsh: "DeepSeek Harness" }[source.toLowerCase()] ?? source);
